# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWreb-nCKqEPGlxqYC4m6a58ftSEHt7z
"""

from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
import tensorflow as tf
import numpy as np
from PIL import Image
import io

app = FastAPI()

# CORS para que el frontend (localhost o Cloud) pueda llamar al backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # si quieres, luego puedes restringir esto
    allow_methods=["*"],
    allow_headers=["*"],
)

# Cargar el modelo .keras
print("Cargando modelo...")
model = tf.keras.models.load_model("mnist_cnn.keras")
print("Modelo cargado correctamente.")

def preprocess(img_bytes):
    """
    Convierte la imagen a escala de grises, la redimensiona a 28x28 y la
    normaliza igual que en el entrenamiento (0-1, shape (1,28,28,1)).
    """
    img = Image.open(io.BytesIO(img_bytes)).convert("L")  # 'L' = grayscale
    img = img.resize((28, 28))

    arr = np.array(img).astype("float32") / 255.0
    arr = np.expand_dims(arr, axis=-1)   # (28,28) -> (28,28,1)
    arr = np.expand_dims(arr, axis=0)    # (28,28,1) -> (1,28,28,1)
    return arr

@app.get("/")
async def root():
    return {"message": "API MNIST funcionando 🧠✏️"}

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    img_bytes = await file.read()
    x = preprocess(img_bytes)
    preds = model.predict(x)
    digit = int(np.argmax(preds[0]))
    confidence = float(np.max(preds[0]))
    return {
        "digit": digit,
        "confidence": confidence,
        "probabilities": preds[0].tolist()
    }